repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint
        language: system
        types: [python]
        args:
          - --recursive=y
          - --disable=all
          - --enable=E

  - repo: local
    hooks:
      - id: pytest with coverage
        name: pytest
        entry: pytest --cov=. --cov-report=term-missing
        language: system
        pass_filenames: false
