[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel"]
build-backend = 'setuptools.build_meta'

[project]
name = "cloudcatalog"
version = "1.2.2"
authors = [ {name = "Johns Hopkins University Applied Physics Laboratory LLC", email = "sandy.antunes@jhuapl.edu"}]
license = {text = "MIT License"}
description = "API for accessing the generalized CloudCatalog (cloudcatalog) specification for sharing data in and across clouds"
readme = "README.md"
keywords = ["cloud","index","catalog","AWS"]
classifiers=[
        "Development Status :: 4 - Beta",
        "Topic :: Utilities",
        "License :: OSI Approved :: MIT License",
        ]
requires-python = ">=3.9"
dependencies = [
    "boto3",
    "pandas",
    ]

[project.urls]
Homepage = "https://heliocloud.org"
Documentation = "https://github.com/heliocloud-data/cloudcatalog"
Repository = "https://github.com/heliocloud-data/cloudcatalog"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib",]

[tool.black]
include = '\.py'

[project.scripts]
cloudcatalog-update-json = "cloudcatalog.updater.catalog_updater:update_json_main"
cloudcatalog-update-csv = "cloudcatalog.updater.catalog_updater:update_csv_main"
cloudcatalog-gui = "cloudcatalog.catalogtools.catalog_updater:updater_gui"
cloudcatalog-tree = "cloudcatalog.cloudspider:tree_main"
cloudcatalog-spider = "cloudcatalog.cloudspider:spider_main"
cloudcatalog-manifest2indices = "cloudcatalog.generators:m2i_main"
